In [19]:
# for data manipulation and analysis
import pandas as pd

# Writing to a CSV File
import csv

# for better display
from IPython.display import display

# for vizualization
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

# Numerical computing
import numpy as np

import math

from deep_translator import GoogleTranslator

import us

In [2]:
def wrangle(filepath):
    # Load data
    df = pd.read_excel(filepath)

    return df

In [3]:
filepath = r"C:\Users\KINGLEY EYO\Documents\supply_chain_sql_clean.xlsx"
df = wrangle(filepath)

In [4]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Customer Name
0,PAYMENT,5,2,22.799999,113.980003,Late delivery,1,17,Cleats,Las Vegas,...,Nelson,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-04-02 18:59:00,Second Class,Dorothy Carter
1,PAYMENT,6,2,37.419998,113.379997,Late delivery,1,17,Cleats,Garland,...,Fujian,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-02-09 13:48:00,Second Class,Mary Harding
2,PAYMENT,5,2,30.570000,109.180000,Late delivery,1,17,Cleats,Columbus,...,Daca,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-03-23 04:59:00,Second Class,Mary Wright
3,PAYMENT,6,2,28.080000,107.980003,Late delivery,1,17,Cleats,Potomac,...,Queensland,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-02-09 05:02:00,Second Class,Aaron Smith
4,PAYMENT,2,2,38.009998,105.580002,Shipping on time,0,17,Cleats,New Orleans,...,Capital Nacional,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2015-12-07 07:14:00,Second Class,Lori Mccarthy

In [8]:
cols_to_translate = ['Customer City', 'Customer Country', 'Order Country', 'Order State', 'Order City']

for col in cols_to_translate:
    print(f"Translating column: {col}")
    
    unique_vals = df[col].dropna().unique()
    translation_map = {}
    
    for val in unique_vals:
        try:
            translated = GoogleTranslator(source='auto', target='en').translate(val)
            translation_map[val] = translated
        except Exception as e:
            print(f"Error translating '{val}': {e}")
            translation_map[val] = val  # fallback: keep original
    
    df[col] = df[col].map(translation_map)

Translating column: Customer City
Translating column: Customer Country
Translating column: Order Country
Translating column: Order State
Error translating 'Saga': ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Translating column: Order City

In [9]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Customer Name
0,PAYMENT,5,2,22.799999,113.980003,Late delivery,1,17,Cleats,Las Vegas,...,Nelson,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-04-02 18:59:00,Second Class,Dorothy Carter
1,PAYMENT,6,2,37.419998,113.379997,Late delivery,1,17,Cleats,Garland,...,Fujian,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-02-09 13:48:00,Second Class,Mary Harding
2,PAYMENT,5,2,30.570000,109.180000,Late delivery,1,17,Cleats,Columbus,...,Daca,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-03-23 04:59:00,Second Class,Mary Wright
3,PAYMENT,6,2,28.080000,107.980003,Late delivery,1,17,Cleats,Potomac,...,Queensland,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2016-02-09 05:02:00,Second Class,Aaron Smith
4,PAYMENT,2,2,38.009998,105.580002,Shipping on time,0,17,Cleats,New Orleans,...,National Capital,PENDING_PAYMENT,365,17,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,2015-12-07 07:14:00,Second Class,Lori Mccarthy

In [10]:
df.to_csv('translated_dataset.csv', index=False)

In [13]:
df['Customer Country'].unique()

array(['Of. His.', 'Puerto Rico'], dtype=object)

In [14]:
# Replace "Of. His." with "United States" in Customer Country column
df['Customer Country'] = df['Customer Country'].replace('Of. His.', 'United States')


print(df['Customer Country'].unique())

['United States' 'Puerto Rico']

In [22]:
# Select only 'Customer Country' and 'Customer State'
selected_columns = df[['Customer Country', 'Customer State']]

print(selected_columns.tail())

       Customer Country Customer State
180535    United States             CA
180536    United States             CA
180537      Puerto Rico             PR
180538    United States             IL
180539    United States             IL

In [26]:
# Map abbreviations to full names
state_mapping = {state.abbr: state.name for state in us.states.STATES}
state_mapping['PR'] = 'Puerto Rico'

# Create new column with full names
df['Customer State Full'] = df['Customer State'].map(state_mapping)

# Select relevant columns including the new one
statess = df[['Customer Country', 'Customer State', 'Customer State Full']]


print(statess.tail())

       Customer Country Customer State Customer State Full
180535    United States             CA          California
180536    United States             CA          California
180537      Puerto Rico             PR         Puerto Rico
180538    United States             IL            Illinois
180539    United States             IL            Illinois

In [27]:
df.tail()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,shipping date (DateOrders),Shipping Mode,Customer Name,Customer State Full
180535,DEBIT,3,4,93.959999,199.919998,Advance shipping,0,46,Indoor/Outdoor Games,Modesto,...,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.98,2015-06-07 14:29:00,Standard Class,Angela Sanford,California
180536,DEBIT,3,4,9.020000,47.480000,Advance shipping,0,46,Indoor/Outdoor Games,Modesto,...,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.98,2015-06-07 14:29:00,Standard Class,Angela Sanford,California
180537,TRANSFER,5,4,59.740002,124.449997,Late delivery,1,46,Indoor/Outdoor Games,Caguas,...,PROCESSING,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.98,2015-06-09 13:26:00,Standard Class,Sharon Moore,Puerto Rico
180538,DEBIT,3,4,21.730000,47.230000,Advance shipping,0,46,Indoor/Outdoor Games,Aurora,...,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.98,2015-06-07 12:44:00,Standard Class,Emily Smith,Illinois
180539,DEBIT,3,4,89.959999,187.429993,Advance shipping,0,46,Indoor/Outdoor Games,Aurora,...,COMPLETE,1014,46,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.98,2015-06-07 12:44:00,Standard Class,Emily Smith,Illinois

In [28]:
# Replace values in the 'Market' column
df['Market'] = df['Market'].replace({
    'LATAM': 'Latin America',
    'USCA': 'United States and Canada'
})

print(df['Market'].unique())

['Pacific Asia' 'United States and Canada' 'Africa' 'Europe'
 'Latin America']

In [29]:
df['Order Country'] = df['Order Country'].replace('TÃ¼rkiye', 'Turkey')

In [30]:
df['Order Country'] = df['Order Country'].replace('Filipinas', 'Philippines')

In [31]:
df['Order Country'] = df['Order Country'].replace('Myanmar (Birmania)', 'Myanmar')

In [32]:
df['Order Country'] = df['Order Country'].replace('Italia', 'Italy')

In [33]:
df['Order Country'] = df['Order Country'].replace('Space', 'Spain')

In [34]:
df['Order Country'] = df['Order Country'].replace('Guadalupe', 'Guadeloupe')

In [36]:
df['Order Country'] = df['Order Country'].replace('Camboya', 'Cambodia')

In [35]:
distinct_order_countries = df['Order Country'].unique()

print(distinct_order_countries)

['New Zealand' 'China' 'Bangladesh' 'Australia' 'Philippines' 'Camboya'
 'Kyrguistan' 'Indonesia' 'Iran' 'India' 'Nepal' 'Myanmar' 'Turkey'
 'Israel' 'Thailand' 'USA' 'Canada' 'Egypt' 'Ivory coast'
 'Congo Democratic Republic' 'Nigeria' 'Togo' 'Zimbabwe' 'Senegal'
 'Mozambique' 'Gabon' 'Sudan' 'United Kingdom' 'Moldavia' 'France'
 'Belgium' 'Austria' 'Netherlands' 'Germany' 'Ukraine' 'Italy' 'Sweden'
 'Ireland' 'Spain' 'Poland' 'Brazil' 'Dominican Republic' 'Cuba'
 'Guadeloupe' 'Nicaragua' 'Mexico' 'Guatemala' 'Colombia' 'Chile'
 'El Salvador' 'Honduras' 'Panama' 'Venezuela' 'Ecuador' 'Peru'
 'Turkmenistan' 'Singapore' 'Malaysia' 'Japan' 'Afghanistan'
 'Saudi Arabia' 'Papua New Guinea' 'Pakistan' 'Irak' 'Haiti' 'Paraguay'
 'Argentina' 'Bolivia' 'Russia' 'Finlandia' 'Norway'
 'Bosnia and Herzegovina' 'Hungary' 'Bulgaria' 'Czech Republic' 'Denmark'
 'Portugal' 'Swiss' 'Rumania' 'Belarus' 'Greece' 'Kenya' 'South Africa'
 'Croatia' 'South Korea' 'Vietnam' 'Cameroon' 'Jamaica' 'Azerbaijan'
 'Georgia' 'Jordan' 'Hong Kong' 'Uganda' 'Morocco' 'Martinique'
 'Kazakhstan' 'Algeria' 'Lithuania' 'Barbados' 'Taiwan' 'Mongolia' 'Yemen'
 'Estonia' 'Ghana' 'Madagascar' 'Somalia' 'Rwanda' 'Niger' 'Angola'
 'Tunisia' 'Zambia' 'Benin' 'Albania' 'Botlyana' 'Qatar' 'Uzbekistan'
 'United Arab Emirates' 'Uruguay' 'Guinea-Bissau' 'Syria' 'Guinea' 'Treat'
 'Mali' 'Libya' 'French Guayana' 'Costa Rica' 'Tanzania' 'Burkina Faso'
 'Surinam' 'Equatorial Guinea' 'Slovakia' 'Yibuti' 'Belice' 'Oman'
 'Cyprus' 'Montenegro' 'Republic of Congo' 'Namibia' 'Liberia'
 'Western Sahara' 'Republic of Gambia' 'Mauritania' 'Guyana'
 'Sierra Leone' 'Central African Republic' 'Chad' 'Lebanon' 'Luxembourg'
 'Lesoto' 'Armenia' 'Sri Lanka' 'Ethiopia' 'Burundi' 'South Sudan'
 'Slovenia' 'Tayikistan' 'Eritrea' 'Macedonia' 'Laos' 'Barine' 'Butane'
 'Swaziland' 'Kuwait' 'Serbia']

In [37]:
# Replace country names with the correct English names
df['Order Country'] = df['Order Country'].replace({
    'Kyrguistan': 'Kyrgyzstan',
    'Finlandia': 'Finland',
    'Swiss': 'Switzerland',
    'Rumania': 'Romania',
    'Botlyana': 'Botswana',
    'Treat': 'Trinidad and Tobago',
    'Surinam': 'Suriname',
    'Yibuti': 'Djibouti',
    'Belice': 'Belize',
    'Tayikistan': 'Tajikistan',
    'Barine': 'Bahrain'
})

In [38]:
df.to_csv(r'C:\Users\KINGLEY EYO\Documents\supplychain_complaint-cleaned_data.csv', index=False)

In [ ]:
df.head()